version: '3.8'
services:
  app:
    container_name: alpaca-webui
    image: alpaca-webui:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - net
    ports:
      - '3033:3000'

  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.7
    ports:
      - 8080:8080
      - 50051:50051
    restart: on-failure:0
    networks:
      - net
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'

networks:
  net:
    driver: bridge
